config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  get 'main/users'

  get 'main/blogs'

  root "main#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :users
  # , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :setUser


  private
  def setUser
	 @current_user = current_user
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def users

    @users = User.all
    @user = current_user

  end

  def blogs
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
	puts "@@@@@@@@@@@@@@@@@@"
	puts request.env["omniauth.auth"]
	puts @user
	puts "@@@@@@@@@@@@@@@@@@"

	for attribute in @user.attributes.keys do
		puts attribute.humanize.to_s+" heii "+ @user.attributes[attribute].to_s
	end
	puts "##########################"

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li>
      	<%= link_to "Home", main_index_path %>
      </li>
      <li>
        	<%= link_to "Users",  main_users_path  %>
      </li>
      <li>
        	<%= link_to "Login",  main_users_path  %>
      </li>

      <li>
        	<%= link_to "LogOut",  destroy_user_session_path, method: 'delete' %>
      </li>

      <li>
        	<%= link_to "Register",   new_user_registration_path   %>
      </li>

     <li>
        	<%= link_to "Login with Facebook",    user_facebook_omniauth_authorize_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bekbolot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= if @current_user
          @current_user.email
        end

    %>

    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/main/blogs.html.erb
<h1>Main#blogs</h1>
<p>Find me in app/views/main/blogs.html.erb</p>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/main/users.html.erb
<h1>Main#users</h1>
<p>Find me in app/views/main/users.html.erb</p>


<% if @current_user %>
<p>
You are:<strong> <%=
@current_user.email
%> </strong>
<br> <%=  @current_user.password  %>
</p>

<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="row">
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>



</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>